pipeline:
  test:
    image: rust:1.61
    commands:
      - cargo build --no-default-features
      - cargo test --no-default-features

  publish_latest:
    image: plugins/docker
    repo: seabirdchat/seabird-core
    tags: latest
    secrets: [ docker_username, docker_password ]
    when:
      branch: main

  publish_next:
    image: plugins/docker
    repo: seabirdchat/seabird-core
    tags: next
    secrets: [ docker_username, docker_password ]
    when:
      branch: develop
