# Stage 1: Build the application
FROM golang:1.14-buster as builder

RUN apt-get update && apt-get install -y protobuf-compiler && rm -rf /var/lib/apt/lists/*
RUN go get google.golang.org/protobuf/cmd/protoc-gen-go
RUN go get google.golang.org/grpc/cmd/protoc-gen-go-grpc

RUN mkdir /build
RUN mkdir -p /seabird-core/{proto,go,go/pb}

WORKDIR /seabird-core/go
ADD ./go/go.mod ./go/go.sum ./
RUN go mod download

WORKDIR /seabird-core
ADD ./proto/* /seabird-core/proto/

WORKDIR /seabird-core/go

ADD ./go/pb/ ./pb/
RUN go generate ./...

ADD ./go/ ./
RUN go build -v -o /build/seabird-core ./cmd/seabird-core

# Stage 2: Copy files and configure what we need
FROM debian:buster-slim

RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

# Copy the built seabird into the container
COPY --from=builder /build /bin

EXPOSE 11235

ENTRYPOINT ["/bin/seabird-core"]
