name: Nix Build

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Nix targets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3
      - name: Build default package
        run: nix build
